### ISSUE TITLE
Build error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by 0pcom** [snipcart/sleekypay#6]
After following the readme instructions, I get:

```
Build error: Cannot read property 'length' of undefined
```
on http://localhost:1234/index.html

here's the terminal output

```
[user@linux  sleekypay]$ sudo npm install netlify-cli -g
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
/usr/bin/ntl -> /usr/lib/node_modules/netlify-cli/bin/run
/usr/bin/netlify -> /usr/lib/node_modules/netlify-cli/bin/run

> netlify-cli@2.65.1 postinstall /usr/lib/node_modules/netlify-cli
> node ./scripts/postinstall.js


Success! Netlify CLI has been installed!

Your device is now configured to use Netlify CLI to deploy and manage your Netlify sites.

Next steps:

  netlify init     Connect or create a Netlify site from current directory
  netlify deploy   Deploy the latest changes to your Netlify site

For more information on the CLI run netlify help
Or visit the docs at https://cli.netlify.com

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/netlify-cli/node_modules/rollup/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ netlify-cli@2.65.1
added 245 packages from 133 contributors, removed 7 packages and updated 8 packages in 39.312s
[user@linux  sleekypay]$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 14.819s

24 packages are looking for funding
  run `npm fund` for details

[user@linux  sleekypay]$ npm run dev

> sleekypay@1.0.0 dev /home/user/WEB/SNIPCART/sleekypay
> concurrently --kill-others "npm run website:dev" "npm run functions:dev"

[1] 
[1] > sleekypay@1.0.0 functions:dev /home/user/WEB/SNIPCART/sleekypay
[1] > concurrently --kill-others "parcel ./src/functions/*.ts --out-dir dist/functions --target node" "parcel ./src/functions/bin/*.ts --out-dir dist/functions/bin --target node"
[1] 
[0] 
[0] > sleekypay@1.0.0 website:dev /home/user/WEB/SNIPCART/sleekypay
[0] > parcel ./src/index.html ./src/assets/*
[0] 
[0] Server running at http://localhost:1234 
⚠️  Parser "assets/JSAsset" failed to initialize when processing asset "node_modules/parcel-bundler/src/builtins/css-loader.js". Threw the following error:
[0] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/user/WEB/SNIPCART/sleekypay/node_modules/@babel/helper-compilation-targets/package.json
[0]     at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
[0]     at packageExportsResolve (internal/modules/esm/resolve.js:496:3)
[0]     at resolveExports (internal/modules/cjs/loader.js:450:36)
[0]     at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
[0]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:27)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:743:27)
[0]     at Module.require (internal/modules/cjs/loader.js:965:19)
[0]     at require (/home/user/WEB/SNIPCART/sleekypay/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
[0]     at Object.<anonymous> (/home/user/WEB/SNIPCART/sleekypay/node_modules/@babel/preset-env/lib/debug.js:8:33)
[0]     at Module._compile (/home/user/WEB/SNIPCART/sleekypay/node_modules/v8-compile-cache/v8-compile-cache.js:194:30) falling back to RawAsset
[0] 🚨  Cannot read property 'length' of undefined
[0]     at lineCounter (/home/user/WEB/SNIPCART/sleekypay/node_modules/parcel-bundler/src/utils/lineCounter.js:3:30)
[0]     at JSPackager.writeModule (/home/user/WEB/SNIPCART/sleekypay/node_modules/parcel-bundler/src/packagers/JSPackager.js:127:60)
[0]     at async JSPackager.addAsset (/home/user/WEB/SNIPCART/sleekypay/node_modules/parcel-bundler/src/packagers/JSPackager.js:88:5)
[0]     at async Bundle._addDeps (/home/user/WEB/SNIPCART/sleekypay/node_modules/parcel-bundler/src/Bundle.js:250:5)
[0]     at async Bundle._addDeps (/home/user/WEB/SNIPCART/sleekypay/node_modules/parcel-bundler/src/Bundle.js:247:7)
[0]     at async Bundle._package (/home/user/WEB/SNIPCART/sleekypay/node_modules/parcel-bundler/src/Bundle.js:219:7)
[0]     at async Promise.all (index 0)
[0]     at async Bundle.package (/home/user/WEB/SNIPCART/sleekypay/node_modules/parcel-bundler/src/Bundle.js:202:5)
[0]     at async Promise.all (index 1)
[0]     at async Bundle.package (/home/user/WEB/SNIPCART/sleekypay/node_modules/parcel-bundler/src/Bundle.js:202:5)
[0] ⚠️  Parser "assets/JSAsset" failed to initialize when processing asset "node_modules/parcel-bundler/src/builtins/hmr-runtime.js". Threw the following error:
[0] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/user/WEB/SNIPCART/sleekypay/node_modules/@babel/helper-compilation-targets/package.json
[0]     at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
[0]     at packageExportsResolve (internal/modules/esm/resolve.js:496:3)
[0]     at resolveExports (internal/modules/cjs/loader.js:450:36)
[0]     at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
[0]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:27)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:743:27)
[0]     at Module.require (internal/modules/cjs/loader.js:965:19)
[0]     at require (/home/user/WEB/SNIPCART/sleekypay/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
[0]     at Object.<anonymous> (/home/user/WEB/SNIPCART/sleekypay/node_modules/@babel/preset-env/lib/debug.js:8:33)
[0]     at Module._compile (/home/user/WEB/SNIPCART/sleekypay/node_modules/v8-compile-cache/v8-compile-cache.js:194:30) falling back to RawAsset
✨  Built in 74ms.
[1] [1] ✨  Built in 87ms.
^C[0] npm run website:dev exited with code 0
--> Sending SIGTERM to other processes..
[1] [0] parcel ./src/functions/*.ts --out-dir dist/functions --target node exited with code SIGINT
[1] --> Sending SIGTERM to other processes..
[1] [1] parcel ./src/functions/bin/*.ts --out-dir dist/functions/bin --target node exited with code SIGINT
[1] npm run functions:dev exited with code 0
[user@linux  sleekypay]$ sudo npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 948 packages in 5.149s

24 packages are looking for funding
  run `npm fund` for details

found 233 vulnerabilities (220 low, 3 moderate, 10 high)
  run `npm audit fix` to fix them, or `npm audit` for details


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New patch version of npm available! 6.14.7 → 6.14.8       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.14.8   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

[user@linux  sleekypay]$ sudo npm run dev

> sleekypay@1.0.0 dev /home/user/WEB/SNIPCART/sleekypay
> concurrently --kill-others "npm run website:dev" "npm run functions:dev"

[0] 
[0] > sleekypay@1.0.0 website:dev /home/user/WEB/SNIPCART/sleekypay
[0] > parcel ./src/index.html ./src/assets/*
[0] 
[1] 
[1] > sleekypay@1.0.0 functions:dev /home/user/WEB/SNIPCART/sleekypay
[1] > concurrently --kill-others "parcel ./src/functions/*.ts --out-dir dist/functions --target node" "parcel ./src/functions/bin/*.ts --out-dir dist/functions/bin --target node"
[1] 
[0] Server running at http://localhost:1234 
⚠️  Parser "assets/JSAsset" failed to initialize when processing asset "node_modules/parcel-bundler/src/builtins/css-loader.js". Threw the following error:
[0] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/user/WEB/SNIPCART/sleekypay/node_modules/@babel/helper-compilation-targets/package.json
[0]     at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
[0]     at packageExportsResolve (internal/modules/esm/resolve.js:496:3)
[0]     at resolveExports (internal/modules/cjs/loader.js:450:36)
[0]     at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
[0]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:27)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:743:27)
[0]     at Module.require (internal/modules/cjs/loader.js:965:19)
[0]     at require (/home/user/WEB/SNIPCART/sleekypay/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
[0]     at Object.<anonymous> (/home/user/WEB/SNIPCART/sleekypay/node_modules/@babel/preset-env/lib/debug.js:8:33)
[0]     at Module._compile (/home/user/WEB/SNIPCART/sleekypay/node_modules/v8-compile-cache/v8-compile-cache.js:194:30) falling back to RawAsset
[0] 🚨  Cannot read property 'length' of undefined
[0]     at lineCounter (/home/user/WEB/SNIPCART/sleekypay/node_modules/parcel-bundler/src/utils/lineCounter.js:3:30)
[0]     at JSPackager.writeModule (/home/user/WEB/SNIPCART/sleekypay/node_modules/parcel-bundler/src/packagers/JSPackager.js:127:60)
[0]     at async JSPackager.addAsset (/home/user/WEB/SNIPCART/sleekypay/node_modules/parcel-bundler/src/packagers/JSPackager.js:88:5)
[0]     at async Bundle._addDeps (/home/user/WEB/SNIPCART/sleekypay/node_modules/parcel-bundler/src/Bundle.js:250:5)
[0]     at async Bundle._addDeps (/home/user/WEB/SNIPCART/sleekypay/node_modules/parcel-bundler/src/Bundle.js:247:7)
[0]     at async Bundle._package (/home/user/WEB/SNIPCART/sleekypay/node_modules/parcel-bundler/src/Bundle.js:219:7)
[0]     at async Promise.all (index 0)
[0]     at async Bundle.package (/home/user/WEB/SNIPCART/sleekypay/node_modules/parcel-bundler/src/Bundle.js:202:5)
[0]     at async Promise.all (index 1)
[0]     at async Bundle.package (/home/user/WEB/SNIPCART/sleekypay/node_modules/parcel-bundler/src/Bundle.js:202:5)
[0] ⚠️  Parser "assets/JSAsset" failed to initialize when processing asset "node_modules/parcel-bundler/src/builtins/hmr-runtime.js". Threw the following error:
[0] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/user/WEB/SNIPCART/sleekypay/node_modules/@babel/helper-compilation-targets/package.json
[0]     at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
[0]     at packageExportsResolve (internal/modules/esm/resolve.js:496:3)
[0]     at resolveExports (internal/modules/cjs/loader.js:450:36)
[0]     at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
[0]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:27)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:743:27)
[0]     at Module.require (internal/modules/cjs/loader.js:965:19)
[0]     at require (/home/user/WEB/SNIPCART/sleekypay/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
[0]     at Object.<anonymous> (/home/user/WEB/SNIPCART/sleekypay/node_modules/@babel/preset-env/lib/debug.js:8:33)
[0]     at Module._compile (/home/user/WEB/SNIPCART/sleekypay/node_modules/v8-compile-cache/v8-compile-cache.js:194:30) falling back to RawAsset
✨  Built in 83ms.
[1] [1] ✨  Built in 114ms.

```

**Comment by 0pcom** [comment]
solved by running `npm update`
